substitutions:
  _NAMESPACE: default
  _NAME: app-secret
  _VALUE: ""
  _STATE_BUCKET: ""

steps:
  - id: apply-secret
    name: hashicorp/terraform:1.9
    entrypoint: sh
    dir: secret
    env:
      - NAMESPACE=${_NAMESPACE}
      - NAME=${_NAME}
      - VALUE=${_VALUE}
      - STATE_BUCKET=${_STATE_BUCKET}
    args:
      - -c
      - |
        set -e

        sh scripts/gen-tfvars.sh

        terraform init -input=false \
          -backend-config="bucket=$${STATE_BUCKET}" \
          -backend-config="prefix=$${NAME}" 

        terraform apply -input=false -auto-approve
